---
- hosts: workers
  become: yes
  tags:
    - join
  roles:
    - rollback/k8s/join

- hosts: masters
  become: yes
  tags:
    - init
  roles:
    - rollback/k8s/init
    - rollback/flannel

- hosts: all
  become: yes
  tags:
    - setup
  roles:
    - rollback/cni
    - rollback/k8s/common
    - rollback/crio
    - rollback/common
